#!/bin/bash -e

home="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $home/utils

print_header "Installing required packages"
apt-get update 1>/dev/null
apt-get -y install parted kpartx debootstrap extlinux

