#!/bin/bash

if [ -d $img_mount_dir ]; then
  print_header "Unmounting $img_mount_dir"
  set +e
  mounted=true
  while $mounted; do
    msg=`umount $img_mount_dir 2>&1`
    if [ $? = 0 ]; then
      mounted=false
    elif [[ $msg =~ not\ mounted ]]; then
      mounted=false
    else
      echo $msg
      sleep 1
    fi
  done
  set -e
  rm -r $img_mount_dir
fi

find_img_device
if [ ! -z "$img_device" ]; then
  echo "> Removing devices for $img_file"
  kpartx -d $img_file
fi

